In [43]:
# Il s'agit de transformer les données récupérer en dataset propre et exploitable pour la suite

In [44]:
import pandas as pd
from pathlib import Path

In [45]:
RAW_DATA_PATH = Path("../data/raw")
CLEAN_DATA_PATH = Path("../data/cleaned")

CLEAN_DATA_PATH.mkdir(parents=True, exist_ok=True)

In [46]:
df = pd.read_csv(
    RAW_DATA_PATH /
    "BTCUSD_2010-01-01_2025-12-31_raw.csv")

df.head()

,symbol,date,open,high,low,close,volume,change,changePercent,vwap
0,BTCUSD,2025-12-31,88397.24,89100.00,87082.64,87497.94,33830210616,-899.30,-1.017340,88019.4550
1,BTCUSD,2025-12-30,87110.77,89343.52,86704.98,88397.50,35586356225,1286.73,1.477120,87889.1925
2,BTCUSD,2025-12-29,87877.28,90325.00,86675.00,87110.78,48411625849,-766.50,-0.872240,87997.0150
3,BTCUSD,2025-12-28,87806.75,88000.00,87349.52,87877.29,15156557929,70.54,0.080336,87758.3900
4,BTCUSD,2025-12-27,87296.17,87914.62,86944.24,87808.00,13741199310,511.83,0.586310,87490.7575

In [47]:
print(df.shape)

df.info()

(5000, 10)
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   symbol         5000 non-null   str
 1   date           5000 non-null   str
 2   open           5000 non-null   float64
 3   high           5000 non-null   float64
 4   low            5000 non-null   float64
 5   close          5000 non-null   float64
 6   volume         5000 non-null   int64
 7   change         5000 non-null   float64
 8   changePercent  5000 non-null   float64
 9   vwap           5000 non-null   float64
dtypes: float64(7), int64(1), str(2)
memory usage: 390.8 KB

In [48]:
df["date"] = pd.to_datetime(df["date"]) #conversion des dates

In [49]:
df = ( df.sort_values("date").reset_index(drop=True))

# Nous sommes en serie temporelle. Donc l'ordre d'observation 
# est critique.

In [50]:
print( "Doublons :", df.duplicated().sum())

Doublons : 0

In [51]:
df = df.drop_duplicates() #suppression des doublons

In [52]:
missing = (df.isna().sum().sort_values(ascending=False))

print(missing)

# affiichage des valeurs manquantes

symbol           0
date             0
open             0
high             0
low              0
close            0
volume           0
change           0
changePercent    0
vwap             0
dtype: int64

In [53]:
numeric_cols = ["open","high","low","close","volume"]

for col in numeric_cols:

    df[col] = pd.to_numeric(df[col],errors="coerce")

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   symbol         5000 non-null   str
 1   date           5000 non-null   datetime64[us]
 2   open           5000 non-null   float64
 3   high           5000 non-null   float64
 4   low            5000 non-null   float64
 5   close          5000 non-null   float64
 6   volume         5000 non-null   int64
 7   change         5000 non-null   float64
 8   changePercent  5000 non-null   float64
 9   vwap           5000 non-null   float64
dtypes: datetime64[us](1), float64(7), int64(1), str(1)
memory usage: 390.8 KB

In [55]:
df.describe()

,date,open,high,low,close,volume,change,changePercent,vwap
count,5000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000,5000.000000,5000.000000
mean,2019-02-26 03:18:08.640000,22164.914346,22642.166264,21652.268478,22182.433391,1.819920e+10,17.519045,0.273225,22160.445620
min,2012-04-17 00:00:00,4.850000,4.998800,4.801000,4.850000,0.000000e+00,-8734.230000,-38.812430,4.902750
25%,2015-09-25 18:00:00,480.476000,503.249925,470.097500,482.432500,0.000000e+00,-71.070000,-1.239208,484.843125
50%,2019-02-26 12:00:00,7770.820000,8046.495000,7504.060000,7783.245000,9.722978e+09,0.188455,0.143040,7755.186250
75%,2022-07-30 06:00:00,33949.617500,34913.267500,32541.250000,34028.592500,2.991379e+10,97.415000,1.767302,34008.736875
max,2025-12-31 00:00:00,124723.570000,126296.000000,123115.770000,124720.090000,3.509679e+11,8343.040000,48.768950,124413.165000
std,NaN,30459.402931,31007.948859,29875.155413,30471.797031,2.317826e+10,1003.942369,4.048110,30449.161203

In [ ]:

# l'historique réellement disponible via FMP commence à partir du 17/04/2012.
# Le nom du fichier est conservé afin de maintenir une cohérence dans la structure du projet.

In [56]:
df.to_csv( CLEAN_DATA_PATH / "BTCUSD_clean.csv", index=False )

print("Dataset nettoyé sauvegardé.")

Dataset nettoyé sauvegardé.